name: flake8

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-html
    - name: Analysing the code with flake
      
      run: |
        flake8 --format=html --htmldir=flake-report `ls -R|grep .py$|xargs`
    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: flake-report
